### ISSUE TITLE
tight coupling with koop-pgcache

### ISSUE THREAD

**Issue by ungoldman** [GeoXForm/spatialreference#1]
It seems like spatialreference is very tightly coupled to the way koop's postgis cache adapter works (`options.db` is not really for a database but for `koop-pgcache`). What do you think about evolving this module a bit to be more usable for projects outside of koop?

**Comment by dmfenton** [comment]
Well, actually its not really that tightly coupled with Koop-PGCache. It will work just fine if there's no db passed in.

A passed in DB only needs to support `getWKT` and `insertWKT` to work. Doesn't that make this pretty usable outside Koop? What else when you recommend?

**Comment by ungoldman** [comment]
> Well, actually its not really that tightly coupled with Koop-PGCache. It will work just fine if there's no db passed in.

It might help to make the example show that in the README.

> A passed in DB only needs to support getWKT and insertWKT to work. Doesn't that make this pretty usable outside Koop? What else when you recommend?

Do you know any database clients that have that out of the box?

**Comment by dmfenton** [comment]
:+1: To an example.

> Do you know any database clients that have that out of the box?

No, but how is this module supposed to support a redis, elasticsearch or even another SQL implementation without delegating that to a getWKT or insertWKT with client specific logic?

**Comment by dmfenton** [comment]
@ngoldman do you have a better solution or can I close?

**Comment by dmfenton** [comment]
@ngoldman feel free to reopen but I think we are good to close.
